### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Percapio** [Percapio/Codex#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Bug-free navigation
- [x] User seeds added

**Comment by wongshington** [comment]
- [ ]  logout button

**Comment by Percapio** [comment]
Fixed all additional changes that need to be made.

**Comment by wongshington** [comment]
- [ ] clears errors when you toggle between login and sign up
- [ ] error messages should be a different color(generally red)
- [ ] also the log out button appears, but disappears sometimes when you try and move the mouse to click on it

**Comment by Percapio** [comment]
1. for the first fix:  I have, below in my session component.  My understanding is that this should trigger after every render, yet its not.  Do you have any ideas?
```
componentDidMount() {
		this.props.clearErrors();
	}
```
3. for the last fix:  I added a transition-duration, and it seems to work for me.  Please, let me know if it doesn't.

**Comment by wongshington** [comment]
- [ ]  maybe just make the font size on the errors a little bit smaller so that they don't look so squished, that or make the component a little bit wider so that when the errors appear they don't look so out of place on the display

**Comment by Percapio** [comment]
I did both, since a bigger container does look better
